import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Link from "next/Link"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Guzzler13</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Guzzler13</a>
        </h1>
        <nav className={styles.nav}>
          <Link className={styles.a} href="/contact">
            Contact
          </Link>
        </nav>
      </main>
    </div>
  )
}
